/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timeout.h"


void
wait_deprecated(CLIENT *clnt, int time)
{
	int  *result_1;
  int param = time * time;
	printf("send %d\n", param);
	result_1 = wait_1(&param, clnt);
	printf("test");
	if (result_1 == (int *) NULL) {
		fprintf(stderr, "Client time out\n");
		exit(0);
	}
}


int
main (int argc, char *argv[])
{
  CLIENT *clnt;
  if (argc!=3) {
    fprintf(stderr,"Usage: %s hostname time\n",argv[0]);
    exit(0);
  }

  clnt = clnt_create(argv[1], timeout_prg, timeout_vrs, "udp");

  struct timeval tv;
  tv.tv_sec = atoi(argv[2]);
  tv.tv_usec = 0;
  clnt_control(clnt, CLSET_TIMEOUT, &tv);

  /* Make sure the create worked */
  if (clnt == (CLIENT *) NULL) {
    clnt_pcreateerror(argv[1]);
    exit(1);
  }

	wait_deprecated(clnt, atoi(argv[2]));
  return(0);
}
