/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timeout.h"

int *
wait_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Wait for %d\n", *argp);
	sleep(*argp);
	printf("...\n");
	result = *argp;
	return &result;
}
