/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMEOUT_H_RPCGEN
#define _TIMEOUT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define timeout_prg 0x20000001
#define timeout_vrs 1

#if defined(__STDC__) || defined(__cplusplus)
#define wait 1
extern  int * wait_1(int *, CLIENT *);
extern  int * wait_1_svc(int *, struct svc_req *);
extern int timeout_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define wait 1
extern  int * wait_1();
extern  int * wait_1_svc();
extern int timeout_prg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMEOUT_H_RPCGEN */
