/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOLA_H_RPCGEN
#define _HOLA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define display_prg 0x20000001
#define display_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define print_hola 1
extern  int * print_hola_1(int *, CLIENT *);
extern  int * print_hola_1_svc(int *, struct svc_req *);
extern int display_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print_hola 1
extern  int * print_hola_1();
extern  int * print_hola_1_svc();
extern int display_prg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOLA_H_RPCGEN */
