/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hola.h"

int *
print_hola_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
		printf("que onda\n");
		sleep(10);
	/*
	 * insert server code here
	 */

	return &result;
}
