/* Generated By:JavaCC: Do not edit this line. SLParserConstants.java */
package jade.content.lang.sl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int HEXINTEGER = 9;
  /** RegularExpression Id. */
  int FLOATONE = 10;
  /** RegularExpression Id. */
  int FLOATTWO = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int STRING_LITERAL = 13;
  /** RegularExpression Id. */
  int PARAMETERNAME = 14;
  /** RegularExpression Id. */
  int PARAMETERNAME_STRING = 15;
  /** RegularExpression Id. */
  int DATETIME = 16;
  /** RegularExpression Id. */
  int PREFIXBYTELENGTHENCODEDSTRING = 17;
  /** RegularExpression Id. */
  int METASYMBOL = 18;
  /** RegularExpression Id. */
  int LBRACE2 = 23;
  /** RegularExpression Id. */
  int RBRACE2 = 24;
  /** RegularExpression Id. */
  int ACTION = 25;
  /** RegularExpression Id. */
  int REFERENTIALOP = 26;
  /** RegularExpression Id. */
  int MODALOP = 27;
  /** RegularExpression Id. */
  int ARITHMETICOP = 28;
  /** RegularExpression Id. */
  int ACTIONOP = 29;
  /** RegularExpression Id. */
  int ACTIONOPLL = 30;
  /** RegularExpression Id. */
  int UNARYLOGICALOP = 31;
  /** RegularExpression Id. */
  int BINARYLOGICALOP = 32;
  /** RegularExpression Id. */
  int QUANTIFIER = 33;
  /** RegularExpression Id. */
  int WORD2 = 34;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 35;
  /** RegularExpression Id. */
  int METASYMBOL2 = 36;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int OPERATORSTATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "<VARIABLE>",
    "<INTEGER>",
    "<HEXINTEGER>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<WORD>",
    "<STRING_LITERAL>",
    "<PARAMETERNAME>",
    "<PARAMETERNAME_STRING>",
    "<DATETIME>",
    "<PREFIXBYTELENGTHENCODEDSTRING>",
    "<METASYMBOL>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"action\"",
    "<REFERENTIALOP>",
    "<MODALOP>",
    "<ARITHMETICOP>",
    "<ACTIONOP>",
    "<ACTIONOPLL>",
    "\"not\"",
    "<BINARYLOGICALOP>",
    "<QUANTIFIER>",
    "<WORD2>",
    "<STRING_LITERAL2>",
    "<METASYMBOL2>",
  };

}
